//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VipTest.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SharedResource_ar {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource_ar() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VipTest.Resources.SharedResource.ar", typeof(SharedResource_ar).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مسؤول.
        /// </summary>
        internal static string AdministrativeRoles_Administrator {
            get {
                return ResourceManager.GetString("AdministrativeRoles_Administrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدير فرع.
        /// </summary>
        internal static string AdministrativeRoles_BranchManager {
            get {
                return ResourceManager.GetString("AdministrativeRoles_BranchManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محرر.
        /// </summary>
        internal static string AdministrativeRoles_Editor {
            get {
                return ResourceManager.GetString("AdministrativeRoles_Editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدير.
        /// </summary>
        internal static string AdministrativeRoles_Manager {
            get {
                return ResourceManager.GetString("AdministrativeRoles_Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دعم.
        /// </summary>
        internal static string AdministrativeRoles_Support {
            get {
                return ResourceManager.GetString("AdministrativeRoles_Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم العثور على المشرف.
        /// </summary>
        internal static string AdminNotFound {
            get {
                return ResourceManager.GetString("AdminNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملغى.
        /// </summary>
        internal static string AirportServicesStatus_Canceled {
            get {
                return ResourceManager.GetString("AirportServicesStatus_Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مكتمل.
        /// </summary>
        internal static string AirportServicesStatus_Completed {
            get {
                return ResourceManager.GetString("AirportServicesStatus_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قيد التنفيذ.
        /// </summary>
        internal static string AirportServicesStatus_InProgress {
            get {
                return ResourceManager.GetString("AirportServicesStatus_InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قيد الانتظار.
        /// </summary>
        internal static string AirportServicesStatus_Pending {
            get {
                return ResourceManager.GetString("AirportServicesStatus_Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرفوض.
        /// </summary>
        internal static string AirportServicesStatus_Rejected {
            get {
                return ResourceManager.GetString("AirportServicesStatus_Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصالة.
        /// </summary>
        internal static string AirportServicesTypes_Lounge {
            get {
                return ResourceManager.GetString("AirportServicesTypes_Lounge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأمتعة.
        /// </summary>
        internal static string AirportServicesTypes_Luggage {
            get {
                return ResourceManager.GetString("AirportServicesTypes_Luggage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فيزا كبار الشخصيات.
        /// </summary>
        internal static string AirportServicesTypes_VipVisa {
            get {
                return ResourceManager.GetString("AirportServicesTypes_VipVisa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن حذف مجموعات المستخدمين الافتراضية.
        /// </summary>
        internal static string CanNotDeleteDefaultUserGroups {
            get {
                return ResourceManager.GetString("CanNotDeleteDefaultUserGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقبول.
        /// </summary>
        internal static string CarAcceptanceStatus_Accepted {
            get {
                return ResourceManager.GetString("CarAcceptanceStatus_Accepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معلق.
        /// </summary>
        internal static string CarAcceptanceStatus_Pending {
            get {
                return ResourceManager.GetString("CarAcceptanceStatus_Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرفوض.
        /// </summary>
        internal static string CarAcceptanceStatus_Rejected {
            get {
                return ResourceManager.GetString("CarAcceptanceStatus_Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أكيورا.
        /// </summary>
        internal static string CarBrand_Acura {
            get {
                return ResourceManager.GetString("CarBrand_Acura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أودي.
        /// </summary>
        internal static string CarBrand_Audi {
            get {
                return ResourceManager.GetString("CarBrand_Audi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بي إم دبليو.
        /// </summary>
        internal static string CarBrand_BMW {
            get {
                return ResourceManager.GetString("CarBrand_BMW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بويك.
        /// </summary>
        internal static string CarBrand_Buick {
            get {
                return ResourceManager.GetString("CarBrand_Buick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كاديلاك.
        /// </summary>
        internal static string CarBrand_Cadillac {
            get {
                return ResourceManager.GetString("CarBrand_Cadillac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شيفروليه.
        /// </summary>
        internal static string CarBrand_Chevrolet {
            get {
                return ResourceManager.GetString("CarBrand_Chevrolet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كرايسلر.
        /// </summary>
        internal static string CarBrand_Chrysler {
            get {
                return ResourceManager.GetString("CarBrand_Chrysler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دودج.
        /// </summary>
        internal static string CarBrand_Dodge {
            get {
                return ResourceManager.GetString("CarBrand_Dodge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فورد.
        /// </summary>
        internal static string CarBrand_Ford {
            get {
                return ResourceManager.GetString("CarBrand_Ford", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هوندا.
        /// </summary>
        internal static string CarBrand_Honda {
            get {
                return ResourceManager.GetString("CarBrand_Honda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هيونداي.
        /// </summary>
        internal static string CarBrand_Hyundai {
            get {
                return ResourceManager.GetString("CarBrand_Hyundai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جاغوار.
        /// </summary>
        internal static string CarBrand_Jaguar {
            get {
                return ResourceManager.GetString("CarBrand_Jaguar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جيب.
        /// </summary>
        internal static string CarBrand_Jeep {
            get {
                return ResourceManager.GetString("CarBrand_Jeep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كيا.
        /// </summary>
        internal static string CarBrand_Kia {
            get {
                return ResourceManager.GetString("CarBrand_Kia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لاند روفر.
        /// </summary>
        internal static string CarBrand_LandRover {
            get {
                return ResourceManager.GetString("CarBrand_LandRover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لكزس.
        /// </summary>
        internal static string CarBrand_Lexus {
            get {
                return ResourceManager.GetString("CarBrand_Lexus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مازدا.
        /// </summary>
        internal static string CarBrand_Mazda {
            get {
                return ResourceManager.GetString("CarBrand_Mazda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرسيدس.
        /// </summary>
        internal static string CarBrand_Mercedes {
            get {
                return ResourceManager.GetString("CarBrand_Mercedes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ميتسوبيشي.
        /// </summary>
        internal static string CarBrand_Mitsubishi {
            get {
                return ResourceManager.GetString("CarBrand_Mitsubishi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نيسان.
        /// </summary>
        internal static string CarBrand_Nissan {
            get {
                return ResourceManager.GetString("CarBrand_Nissan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أخرى.
        /// </summary>
        internal static string CarBrand_Other {
            get {
                return ResourceManager.GetString("CarBrand_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بورش.
        /// </summary>
        internal static string CarBrand_Porsche {
            get {
                return ResourceManager.GetString("CarBrand_Porsche", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سوبارو.
        /// </summary>
        internal static string CarBrand_Subaru {
            get {
                return ResourceManager.GetString("CarBrand_Subaru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تويوتا.
        /// </summary>
        internal static string CarBrand_Toyota {
            get {
                return ResourceManager.GetString("CarBrand_Toyota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فولكس فاجن.
        /// </summary>
        internal static string CarBrand_Volkswagen {
            get {
                return ResourceManager.GetString("CarBrand_Volkswagen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فولفو.
        /// </summary>
        internal static string CarBrand_Volvo {
            get {
                return ResourceManager.GetString("CarBrand_Volvo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم العثور على طلب تأجير السيارة.
        /// </summary>
        internal static string CarRentalOrderNotFound {
            get {
                return ResourceManager.GetString("CarRentalOrderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طلب تأجير سيارة غير معلق.
        /// </summary>
        internal static string CarRentalOrderNotPending {
            get {
                return ResourceManager.GetString("CarRentalOrderNotPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم العثور على العميل.
        /// </summary>
        internal static string CustomerNotFound {
            get {
                return ResourceManager.GetString("CustomerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نشط.
        /// </summary>
        internal static string CustomerStatus_Active {
            get {
                return ResourceManager.GetString("CustomerStatus_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غير نشط.
        /// </summary>
        internal static string CustomerStatus_Inactive {
            get {
                return ResourceManager.GetString("CustomerStatus_Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معلق.
        /// </summary>
        internal static string CustomerStatus_Suspended {
            get {
                return ResourceManager.GetString("CustomerStatus_Suspended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم العثور على الأماكن المخصصة.
        /// </summary>
        internal static string DesignatedPlacesNotFound {
            get {
                return ResourceManager.GetString("DesignatedPlacesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من المطار.
        /// </summary>
        internal static string Destiantion_FromAirport {
            get {
                return ResourceManager.GetString("Destiantion_FromAirport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اخرى.
        /// </summary>
        internal static string Destiantion_Other {
            get {
                return ResourceManager.GetString("Destiantion_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إلى المطار.
        /// </summary>
        internal static string Destiantion_ToAirport {
            get {
                return ResourceManager.GetString("Destiantion_ToAirport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم إضافة الخصم.
        /// </summary>
        internal static string DiscountNotAdded {
            get {
                return ResourceManager.GetString("DiscountNotAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم العثور على الخصم.
        /// </summary>
        internal static string DiscountNotFound {
            get {
                return ResourceManager.GetString("DiscountNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الخصم لم يتم تحديثه.
        /// </summary>
        internal static string DiscountNotUpdated {
            get {
                return ResourceManager.GetString("DiscountNotUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الخصم مرفوض او منتهي.
        /// </summary>
        internal static string DiscountNotValid {
            get {
                return ResourceManager.GetString("DiscountNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خدمة تأجير السيارات.
        /// </summary>
        internal static string DiscountServices_CarRentalService {
            get {
                return ResourceManager.GetString("DiscountServices_CarRentalService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خدمة النقل العادية.
        /// </summary>
        internal static string DiscountServices_NormalRideService {
            get {
                return ResourceManager.GetString("DiscountServices_NormalRideService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خدمة النقل لكبار الشخصيات.
        /// </summary>
        internal static string DiscountServices_VipRideService {
            get {
                return ResourceManager.GetString("DiscountServices_VipRideService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السائق خارج الخدمه.
        /// </summary>
        internal static string DriverNotAllowed {
            get {
                return ResourceManager.GetString("DriverNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم العثور على السائق.
        /// </summary>
        internal static string DriverNotFound {
            get {
                return ResourceManager.GetString("DriverNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متاح.
        /// </summary>
        internal static string DriverStatus_Available {
            get {
                return ResourceManager.GetString("DriverStatus_Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غير متصل.
        /// </summary>
        internal static string DriverStatus_Offline {
            get {
                return ResourceManager.GetString("DriverStatus_Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to في رحلة.
        /// </summary>
        internal static string DriverStatus_OnRide {
            get {
                return ResourceManager.GetString("DriverStatus_OnRide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معلق.
        /// </summary>
        internal static string DriverStatus_Suspended {
            get {
                return ResourceManager.GetString("DriverStatus_Suspended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشل في إنشاء طلب تأجير سيارة.
        /// </summary>
        internal static string FailedToCreateCarRentalOrder {
            get {
                return ResourceManager.GetString("FailedToCreateCarRentalOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشل في إنشاء الأماكن المخصصة.
        /// </summary>
        internal static string FailedToCreateDesignatedPlaces {
            get {
                return ResourceManager.GetString("FailedToCreateDesignatedPlaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشل في إنشاء قالب الإشعار.
        /// </summary>
        internal static string FailedToCreateNotificationTemplate {
            get {
                return ResourceManager.GetString("FailedToCreateNotificationTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشل في إنشاء سيارة للإيجار.
        /// </summary>
        internal static string FailedToCreateRentCar {
            get {
                return ResourceManager.GetString("FailedToCreateRentCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشل في إنشاء الرحلة.
        /// </summary>
        internal static string FailedToCreateRide {
            get {
                return ResourceManager.GetString("FailedToCreateRide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشل في إنشاء فاتورة الركوب.
        /// </summary>
        internal static string FailedToCreateRideBilling {
            get {
                return ResourceManager.GetString("FailedToCreateRideBilling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشل في إنشاء تذكرة الدعم.
        /// </summary>
        internal static string FailedToCreateSupportTicket {
            get {
                return ResourceManager.GetString("FailedToCreateSupportTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشل في إنشاء إشعار المستخدم.
        /// </summary>
        internal static string FailedToCreateUserNotification {
            get {
                return ResourceManager.GetString("FailedToCreateUserNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشل في انشاء المركبة.
        /// </summary>
        internal static string FailedToCreateVehicle {
            get {
                return ResourceManager.GetString("FailedToCreateVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشل في إنشاء المستودع.
        /// </summary>
        internal static string FailedToCreateWarehouse {
            get {
                return ResourceManager.GetString("FailedToCreateWarehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشل في حذف فاتورة الرحلة.
        /// </summary>
        internal static string FailedToDeleteRideBilling {
            get {
                return ResourceManager.GetString("FailedToDeleteRideBilling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشل في حذف تذكرة الدعم.
        /// </summary>
        internal static string FailedToDeleteSupportTicket {
            get {
                return ResourceManager.GetString("FailedToDeleteSupportTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشل في الحصول على فاتورة الركوب.
        /// </summary>
        internal static string FailedToGetRideBilling {
            get {
                return ResourceManager.GetString("FailedToGetRideBilling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشل في تحديث طلب تأجير السيارة.
        /// </summary>
        internal static string FailedToUpdateCarRentalOrder {
            get {
                return ResourceManager.GetString("FailedToUpdateCarRentalOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشل في تحديث الأماكن المخصصة.
        /// </summary>
        internal static string FailedToUpdateDesignatedPlaces {
            get {
                return ResourceManager.GetString("FailedToUpdateDesignatedPlaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشل في تحديث سيارة الإيجار.
        /// </summary>
        internal static string FailedToUpdateRentCar {
            get {
                return ResourceManager.GetString("FailedToUpdateRentCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشل في تحديث الرحلة.
        /// </summary>
        internal static string FailedToUpdateRide {
            get {
                return ResourceManager.GetString("FailedToUpdateRide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشل تحديث تذكرة الدعم.
        /// </summary>
        internal static string FailedToUpdateSupportTicket {
            get {
                return ResourceManager.GetString("FailedToUpdateSupportTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشل تحديث مجموعات المستخدمين.
        /// </summary>
        internal static string FailedToUpdateUserGroups {
            get {
                return ResourceManager.GetString("FailedToUpdateUserGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشل في تحديث المركبة.
        /// </summary>
        internal static string FailedToUpdateVehicle {
            get {
                return ResourceManager.GetString("FailedToUpdateVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشل تحديث المستودع.
        /// </summary>
        internal static string FailedToUpdateWarehouse {
            get {
                return ResourceManager.GetString("FailedToUpdateWarehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المكان المفضل لم يتم اضافته.
        /// </summary>
        internal static string FavouritePlaceNotAdded {
            get {
                return ResourceManager.GetString("FavouritePlaceNotAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم العثور على المكان المفضل.
        /// </summary>
        internal static string FavouritePlaceNotFound {
            get {
                return ResourceManager.GetString("FavouritePlaceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المكان المفضل لم يتم تحديثه.
        /// </summary>
        internal static string FavouritePlaceNotUpdated {
            get {
                return ResourceManager.GetString("FavouritePlaceNotUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرمز السري خطأ او الرقم.
        /// </summary>
        internal static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حالة الرحلة غير صالحة.
        /// </summary>
        internal static string InvalidRideStatus {
            get {
                return ResourceManager.GetString("InvalidRideStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأنبار.
        /// </summary>
        internal static string IraqGovernorates_Anbar {
            get {
                return ResourceManager.GetString("IraqGovernorates_Anbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بابل.
        /// </summary>
        internal static string IraqGovernorates_Babil {
            get {
                return ResourceManager.GetString("IraqGovernorates_Babil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بغداد.
        /// </summary>
        internal static string IraqGovernorates_Baghdad {
            get {
                return ResourceManager.GetString("IraqGovernorates_Baghdad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البصرة.
        /// </summary>
        internal static string IraqGovernorates_Basra {
            get {
                return ResourceManager.GetString("IraqGovernorates_Basra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ذي قار.
        /// </summary>
        internal static string IraqGovernorates_DhiQar {
            get {
                return ResourceManager.GetString("IraqGovernorates_DhiQar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ديالى.
        /// </summary>
        internal static string IraqGovernorates_Diyala {
            get {
                return ResourceManager.GetString("IraqGovernorates_Diyala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دهوك.
        /// </summary>
        internal static string IraqGovernorates_Dohuk {
            get {
                return ResourceManager.GetString("IraqGovernorates_Dohuk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أربيل.
        /// </summary>
        internal static string IraqGovernorates_Erbil {
            get {
                return ResourceManager.GetString("IraqGovernorates_Erbil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كربلاء.
        /// </summary>
        internal static string IraqGovernorates_Karbala {
            get {
                return ResourceManager.GetString("IraqGovernorates_Karbala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كركوك.
        /// </summary>
        internal static string IraqGovernorates_Kirkuk {
            get {
                return ResourceManager.GetString("IraqGovernorates_Kirkuk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ميسان.
        /// </summary>
        internal static string IraqGovernorates_Maysan {
            get {
                return ResourceManager.GetString("IraqGovernorates_Maysan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المثنى.
        /// </summary>
        internal static string IraqGovernorates_Muthanna {
            get {
                return ResourceManager.GetString("IraqGovernorates_Muthanna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to النجف.
        /// </summary>
        internal static string IraqGovernorates_Najaf {
            get {
                return ResourceManager.GetString("IraqGovernorates_Najaf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to القادسية.
        /// </summary>
        internal static string IraqGovernorates_Qadisiyyah {
            get {
                return ResourceManager.GetString("IraqGovernorates_Qadisiyyah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صلاح الدين.
        /// </summary>
        internal static string IraqGovernorates_SalahAlDin {
            get {
                return ResourceManager.GetString("IraqGovernorates_SalahAlDin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السليمانية.
        /// </summary>
        internal static string IraqGovernorates_Sulaymaniyah {
            get {
                return ResourceManager.GetString("IraqGovernorates_Sulaymaniyah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to واسط.
        /// </summary>
        internal static string IraqGovernorates_Wasit {
            get {
                return ResourceManager.GetString("IraqGovernorates_Wasit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجدول.
        /// </summary>
        internal static string NotificationStatus_Scheduled {
            get {
                return ResourceManager.GetString("NotificationStatus_Scheduled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الإرسال.
        /// </summary>
        internal static string NotificationStatus_Sent {
            get {
                return ResourceManager.GetString("NotificationStatus_Sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم العثور على قالب الإشعار.
        /// </summary>
        internal static string NotificationTemplateNotFound {
            get {
                return ResourceManager.GetString("NotificationTemplateNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خصم.
        /// </summary>
        internal static string NotificationType_Discount {
            get {
                return ResourceManager.GetString("NotificationType_Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطأ.
        /// </summary>
        internal static string NotificationType_Error {
            get {
                return ResourceManager.GetString("NotificationType_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معلومة.
        /// </summary>
        internal static string NotificationType_Info {
            get {
                return ResourceManager.GetString("NotificationType_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أخرى.
        /// </summary>
        internal static string NotificationType_Other {
            get {
                return ResourceManager.GetString("NotificationType_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اعلان.
        /// </summary>
        internal static string NotificationType_Promotion {
            get {
                return ResourceManager.GetString("NotificationType_Promotion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحديث النظام.
        /// </summary>
        internal static string NotificationType_SystemUpdate {
            get {
                return ResourceManager.GetString("NotificationType_SystemUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحذير.
        /// </summary>
        internal static string NotificationType_Warning {
            get {
                return ResourceManager.GetString("NotificationType_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تعديل الرمز السري بنجاح.
        /// </summary>
        internal static string PasswordResetSuccessfully {
            get {
                return ResourceManager.GetString("PasswordResetSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدفوعه.
        /// </summary>
        internal static string PaymentStatus_Paid {
            get {
                return ResourceManager.GetString("PaymentStatus_Paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غير مدفوعة.
        /// </summary>
        internal static string PaymentStatus_UnPaid {
            get {
                return ResourceManager.GetString("PaymentStatus_UnPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وقت الاستلام في الماضي.
        /// </summary>
        internal static string PickupTimeInThePast {
            get {
                return ResourceManager.GetString("PickupTimeInThePast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موقع مختار.
        /// </summary>
        internal static string PickUpType_ChosenLocation {
            get {
                return ResourceManager.GetString("PickUpType_ChosenLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من المعرض.
        /// </summary>
        internal static string PickUpType_FromWareHouse {
            get {
                return ResourceManager.GetString("PickUpType_FromWareHouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شقة.
        /// </summary>
        internal static string PlaceType_Apartment {
            get {
                return ResourceManager.GetString("PlaceType_Apartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to منزل.
        /// </summary>
        internal static string PlaceType_Home {
            get {
                return ResourceManager.GetString("PlaceType_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آخر.
        /// </summary>
        internal static string PlaceType_Other {
            get {
                return ResourceManager.GetString("PlaceType_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عمل.
        /// </summary>
        internal static string PlaceType_Work {
            get {
                return ResourceManager.GetString("PlaceType_Work", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملغى.
        /// </summary>
        internal static string RentalOrderStatus_Canceled {
            get {
                return ResourceManager.GetString("RentalOrderStatus_Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم استلام السيارة.
        /// </summary>
        internal static string RentalOrderStatus_CarBack {
            get {
                return ResourceManager.GetString("RentalOrderStatus_CarBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم تعد السيارة.
        /// </summary>
        internal static string RentalOrderStatus_CarNotBack {
            get {
                return ResourceManager.GetString("RentalOrderStatus_CarNotBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مكتمل.
        /// </summary>
        internal static string RentalOrderStatus_Completed {
            get {
                return ResourceManager.GetString("RentalOrderStatus_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مؤكد.
        /// </summary>
        internal static string RentalOrderStatus_Confirmed {
            get {
                return ResourceManager.GetString("RentalOrderStatus_Confirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم التسليم.
        /// </summary>
        internal static string RentalOrderStatus_DroppedOff {
            get {
                return ResourceManager.GetString("RentalOrderStatus_DroppedOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قيد الانتظار.
        /// </summary>
        internal static string RentalOrderStatus_Pending {
            get {
                return ResourceManager.GetString("RentalOrderStatus_Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الاستلام.
        /// </summary>
        internal static string RentalOrderStatus_PickedUp {
            get {
                return ResourceManager.GetString("RentalOrderStatus_PickedUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرفوض.
        /// </summary>
        internal static string RentalOrderStatus_Rejected {
            get {
                return ResourceManager.GetString("RentalOrderStatus_Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم العثور على سيارة للإيجار.
        /// </summary>
        internal static string RentCarNotFound {
            get {
                return ResourceManager.GetString("RentCarNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المراجعه غير موجوده.
        /// </summary>
        internal static string ReviewNotFound {
            get {
                return ResourceManager.GetString("ReviewNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع فاتورة الركوب موجود بالفعل.
        /// </summary>
        internal static string RideBillingTypeAlreadyExist {
            get {
                return ResourceManager.GetString("RideBillingTypeAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم تصل الرحلة إلى مكان الاستلام.
        /// </summary>
        internal static string RideNotArrivedAtPickup {
            get {
                return ResourceManager.GetString("RideNotArrivedAtPickup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم العثور على الرحلة.
        /// </summary>
        internal static string RideNotFound {
            get {
                return ResourceManager.GetString("RideNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بطاقة.
        /// </summary>
        internal static string RidePaymentType_Card {
            get {
                return ResourceManager.GetString("RidePaymentType_Card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نقدي.
        /// </summary>
        internal static string RidePaymentType_Cash {
            get {
                return ResourceManager.GetString("RidePaymentType_Cash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محفظة.
        /// </summary>
        internal static string RidePaymentType_Wallet {
            get {
                return ResourceManager.GetString("RidePaymentType_Wallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وصل الى النقطة الثانية.
        /// </summary>
        internal static string RideStatus_ArrivedAtDetour {
            get {
                return ResourceManager.GetString("RideStatus_ArrivedAtDetour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وصل إلى نقطة الاستلام.
        /// </summary>
        internal static string RideStatus_ArrivedAtPickup {
            get {
                return ResourceManager.GetString("RideStatus_ArrivedAtPickup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملغى.
        /// </summary>
        internal static string RideStatus_Canceled {
            get {
                return ResourceManager.GetString("RideStatus_Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مكتمل.
        /// </summary>
        internal static string RideStatus_Completed {
            get {
                return ResourceManager.GetString("RideStatus_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مؤكد.
        /// </summary>
        internal static string RideStatus_Confirmed {
            get {
                return ResourceManager.GetString("RideStatus_Confirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قيد الانتظار.
        /// </summary>
        internal static string RideStatus_Pending {
            get {
                return ResourceManager.GetString("RideStatus_Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرفوض.
        /// </summary>
        internal static string RideStatus_Rejected {
            get {
                return ResourceManager.GetString("RideStatus_Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بدأ.
        /// </summary>
        internal static string RideStatus_Started {
            get {
                return ResourceManager.GetString("RideStatus_Started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عادي.
        /// </summary>
        internal static string RideType_Normal {
            get {
                return ResourceManager.GetString("RideType_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عادي من المطار.
        /// </summary>
        internal static string RideType_Normal_From_Airport {
            get {
                return ResourceManager.GetString("RideType_Normal_From_Airport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عادي خارج المدينة.
        /// </summary>
        internal static string RideType_Normal_OutSide_City {
            get {
                return ResourceManager.GetString("RideType_Normal_OutSide_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عادي إلى المطار.
        /// </summary>
        internal static string RideType_Normal_To_Airport {
            get {
                return ResourceManager.GetString("RideType_Normal_To_Airport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عادي إلى المثنى.
        /// </summary>
        internal static string RideType_Normal_To_AlMuthana {
            get {
                return ResourceManager.GetString("RideType_Normal_To_AlMuthana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عادي إلى بابل.
        /// </summary>
        internal static string RideType_Normal_To_Babil {
            get {
                return ResourceManager.GetString("RideType_Normal_To_Babil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عادي إلى ذي قار.
        /// </summary>
        internal static string RideType_Normal_To_DhiQar {
            get {
                return ResourceManager.GetString("RideType_Normal_To_DhiQar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عادي إلى كربلاء.
        /// </summary>
        internal static string RideType_Normal_To_Karbala {
            get {
                return ResourceManager.GetString("RideType_Normal_To_Karbala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عادي إلى ميسان.
        /// </summary>
        internal static string RideType_Normal_To_Maysan {
            get {
                return ResourceManager.GetString("RideType_Normal_To_Maysan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عادي إلى النجف.
        /// </summary>
        internal static string RideType_Normal_To_Najaf {
            get {
                return ResourceManager.GetString("RideType_Normal_To_Najaf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عادي إلى القادسية.
        /// </summary>
        internal static string RideType_Normal_To_Qadisiyah {
            get {
                return ResourceManager.GetString("RideType_Normal_To_Qadisiyah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عادي إلى السماوة.
        /// </summary>
        internal static string RideType_Normal_To_Samawa {
            get {
                return ResourceManager.GetString("RideType_Normal_To_Samawa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عادي إلى واسط.
        /// </summary>
        internal static string RideType_Normal_To_Wasit {
            get {
                return ResourceManager.GetString("RideType_Normal_To_Wasit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كبار الشخصيات.
        /// </summary>
        internal static string RideType_Vip {
            get {
                return ResourceManager.GetString("RideType_Vip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كبار الشخصيات من المطار.
        /// </summary>
        internal static string RideType_Vip_From_Airport {
            get {
                return ResourceManager.GetString("RideType_Vip_From_Airport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كبار الشخصيات خارج المدينة.
        /// </summary>
        internal static string RideType_Vip_OutSide_City {
            get {
                return ResourceManager.GetString("RideType_Vip_OutSide_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كبار الشخصيات إلى المطار.
        /// </summary>
        internal static string RideType_Vip_To_Airport {
            get {
                return ResourceManager.GetString("RideType_Vip_To_Airport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كبار الشخصيات إلى المثنى.
        /// </summary>
        internal static string RideType_Vip_To_AlMuthana {
            get {
                return ResourceManager.GetString("RideType_Vip_To_AlMuthana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كبار الشخصيات إلى بابل.
        /// </summary>
        internal static string RideType_Vip_To_Babil {
            get {
                return ResourceManager.GetString("RideType_Vip_To_Babil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كبار الشخصيات إلى ذي قار.
        /// </summary>
        internal static string RideType_Vip_To_DhiQar {
            get {
                return ResourceManager.GetString("RideType_Vip_To_DhiQar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كبار الشخصيات إلى كربلاء.
        /// </summary>
        internal static string RideType_Vip_To_Karbala {
            get {
                return ResourceManager.GetString("RideType_Vip_To_Karbala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كبار الشخصيات إلى ميسان.
        /// </summary>
        internal static string RideType_Vip_To_Maysan {
            get {
                return ResourceManager.GetString("RideType_Vip_To_Maysan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كبار الشخصيات إلى النجف.
        /// </summary>
        internal static string RideType_Vip_To_Najaf {
            get {
                return ResourceManager.GetString("RideType_Vip_To_Najaf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كبار الشخصيات إلى القادسية.
        /// </summary>
        internal static string RideType_Vip_To_Qadisiyah {
            get {
                return ResourceManager.GetString("RideType_Vip_To_Qadisiyah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كبار الشخصيات إلى السماوة.
        /// </summary>
        internal static string RideType_Vip_To_Samawa {
            get {
                return ResourceManager.GetString("RideType_Vip_To_Samawa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كبار الشخصيات إلى واسط.
        /// </summary>
        internal static string RideType_Vip_To_Wasit {
            get {
                return ResourceManager.GetString("RideType_Vip_To_Wasit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اداري.
        /// </summary>
        internal static string Roles_Admin {
            get {
                return ResourceManager.GetString("Roles_Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدير فرع.
        /// </summary>
        internal static string Roles_BranchManager {
            get {
                return ResourceManager.GetString("Roles_BranchManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زبون.
        /// </summary>
        internal static string Roles_Customer {
            get {
                return ResourceManager.GetString("Roles_Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سائق.
        /// </summary>
        internal static string Roles_Driver {
            get {
                return ResourceManager.GetString("Roles_Driver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ألاعدادت غير متاحه.
        /// </summary>
        internal static string SettingsNotFound {
            get {
                return ResourceManager.GetString("SettingsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تلقائي.
        /// </summary>
        internal static string ShifterType_Automatic {
            get {
                return ResourceManager.GetString("ShifterType_Automatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يدوي.
        /// </summary>
        internal static string ShifterType_Manual {
            get {
                return ResourceManager.GetString("ShifterType_Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم العثور على تذكرة الدعم.
        /// </summary>
        internal static string SupportTicketNotFound {
            get {
                return ResourceManager.GetString("SupportTicketNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مغلق.
        /// </summary>
        internal static string TicketStatus_Closed {
            get {
                return ResourceManager.GetString("TicketStatus_Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قيد التنفيذ.
        /// </summary>
        internal static string TicketStatus_InProgress {
            get {
                return ResourceManager.GetString("TicketStatus_InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مفتوح.
        /// </summary>
        internal static string TicketStatus_Open {
            get {
                return ResourceManager.GetString("TicketStatus_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شكوى.
        /// </summary>
        internal static string TicketType_Complaint {
            get {
                return ResourceManager.GetString("TicketType_Complaint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عام.
        /// </summary>
        internal static string TicketType_General {
            get {
                return ResourceManager.GetString("TicketType_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استفسار.
        /// </summary>
        internal static string TicketType_Inquiry {
            get {
                return ResourceManager.GetString("TicketType_Inquiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أخرى.
        /// </summary>
        internal static string TicketType_Other {
            get {
                return ResourceManager.GetString("TicketType_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دفع.
        /// </summary>
        internal static string TicketType_Payment {
            get {
                return ResourceManager.GetString("TicketType_Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استرداد.
        /// </summary>
        internal static string TicketType_Refund {
            get {
                return ResourceManager.GetString("TicketType_Refund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اقتراح.
        /// </summary>
        internal static string TicketType_Suggestion {
            get {
                return ResourceManager.GetString("TicketType_Suggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تقني.
        /// </summary>
        internal static string TicketType_Technical {
            get {
                return ResourceManager.GetString("TicketType_Technical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قيد الانتظار.
        /// </summary>
        internal static string TransactionPaymentStatus_Pending {
            get {
                return ResourceManager.GetString("TransactionPaymentStatus_Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ناجح.
        /// </summary>
        internal static string TransactionPaymentStatus_Successful {
            get {
                return ResourceManager.GetString("TransactionPaymentStatus_Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غير ناجح.
        /// </summary>
        internal static string TransactionPaymentStatus_Unsuccessful {
            get {
                return ResourceManager.GetString("TransactionPaymentStatus_Unsuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خدمة تأجير السيارات.
        /// </summary>
        internal static string TransactionsServicesType_CarRentalService {
            get {
                return ResourceManager.GetString("TransactionsServicesType_CarRentalService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خدمة نقل عادية.
        /// </summary>
        internal static string TransactionsServicesType_NormalRideService {
            get {
                return ResourceManager.GetString("TransactionsServicesType_NormalRideService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خدمة الصالة.
        /// </summary>
        internal static string TransactionsServicesType_VipLoungeService {
            get {
                return ResourceManager.GetString("TransactionsServicesType_VipLoungeService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خدمة الحقائب المفقودة.
        /// </summary>
        internal static string TransactionsServicesType_VipPackageService {
            get {
                return ResourceManager.GetString("TransactionsServicesType_VipPackageService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خدمة نقل كبار الشخصيات.
        /// </summary>
        internal static string TransactionsServicesType_VipRideService {
            get {
                return ResourceManager.GetString("TransactionsServicesType_VipRideService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خدمة الفيزا .
        /// </summary>
        internal static string TransactionsServicesType_VipVisaService {
            get {
                return ResourceManager.GetString("TransactionsServicesType_VipVisaService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المستخدم موجود بالفعل..
        /// </summary>
        internal static string UserAlreadyExists {
            get {
                return ResourceManager.GetString("UserAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم العثور على مجموعات المستخدمين.
        /// </summary>
        internal static string UserGroupsNotFound {
            get {
                return ResourceManager.GetString("UserGroupsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المستخدم ليس زبون.
        /// </summary>
        internal static string UserIsNotACustomer {
            get {
                return ResourceManager.GetString("UserIsNotACustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المستخدم ليس ساىق..
        /// </summary>
        internal static string UserIsNotADriver {
            get {
                return ResourceManager.GetString("UserIsNotADriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المستخدم ليس مدير.
        /// </summary>
        internal static string UserIsNotAnAdmin {
            get {
                return ResourceManager.GetString("UserIsNotAnAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المستخدم ممنوع من تسجيل الدخول.
        /// </summary>
        internal static string UserNotAllowed {
            get {
                return ResourceManager.GetString("UserNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم تتم مصادقة المستخدم.
        /// </summary>
        internal static string UserNotAuthenticated {
            get {
                return ResourceManager.GetString("UserNotAuthenticated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المستخدم غير موجود.
        /// </summary>
        internal static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم العثور على إشعار المستخدم.
        /// </summary>
        internal static string UserNotificationNotFound {
            get {
                return ResourceManager.GetString("UserNotificationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السيارة غير متوفرة.
        /// </summary>
        internal static string VehicleNotAvailable {
            get {
                return ResourceManager.GetString("VehicleNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السيارة غير مخصصة للإيجار.
        /// </summary>
        internal static string VehicleNotForRent {
            get {
                return ResourceManager.GetString("VehicleNotForRent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مركبة غير موجودة.
        /// </summary>
        internal static string VehicleNotFound {
            get {
                return ResourceManager.GetString("VehicleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متاح.
        /// </summary>
        internal static string VehicleStatus_Available {
            get {
                return ResourceManager.GetString("VehicleStatus_Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to في الصيانة.
        /// </summary>
        internal static string VehicleStatus_InMaintenance {
            get {
                return ResourceManager.GetString("VehicleStatus_InMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غير متاح.
        /// </summary>
        internal static string VehicleStatus_NotAvailable {
            get {
                return ResourceManager.GetString("VehicleStatus_NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to في رحلة.
        /// </summary>
        internal static string VehicleStatus_OnTrip {
            get {
                return ResourceManager.GetString("VehicleStatus_OnTrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خارج الخدمة.
        /// </summary>
        internal static string VehicleStatus_OutOfService {
            get {
                return ResourceManager.GetString("VehicleStatus_OutOfService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عادي.
        /// </summary>
        internal static string VehicleType_Normal {
            get {
                return ResourceManager.GetString("VehicleType_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تأجير.
        /// </summary>
        internal static string VehicleType_Rental {
            get {
                return ResourceManager.GetString("VehicleType_Rental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كبار الشخصيات.
        /// </summary>
        internal static string VehicleType_Vip {
            get {
                return ResourceManager.GetString("VehicleType_Vip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشل جلب المستودع.
        /// </summary>
        internal static string WarehouseNotFound {
            get {
                return ResourceManager.GetString("WarehouseNotFound", resourceCulture);
            }
        }
    }
}
