//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VipTest.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SharedResource_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource_en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VipTest.Resources.SharedResource.en", typeof(SharedResource_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator.
        /// </summary>
        internal static string AdministrativeRoles_Administrator {
            get {
                return ResourceManager.GetString("AdministrativeRoles_Administrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch Manager.
        /// </summary>
        internal static string AdministrativeRoles_BranchManager {
            get {
                return ResourceManager.GetString("AdministrativeRoles_BranchManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor.
        /// </summary>
        internal static string AdministrativeRoles_Editor {
            get {
                return ResourceManager.GetString("AdministrativeRoles_Editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager.
        /// </summary>
        internal static string AdministrativeRoles_Manager {
            get {
                return ResourceManager.GetString("AdministrativeRoles_Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        internal static string AdministrativeRoles_Support {
            get {
                return ResourceManager.GetString("AdministrativeRoles_Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Not Found.
        /// </summary>
        internal static string AdminNotFound {
            get {
                return ResourceManager.GetString("AdminNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can Not Delete Default User Groups.
        /// </summary>
        internal static string CanNotDeleteDefaultUserGroups {
            get {
                return ResourceManager.GetString("CanNotDeleteDefaultUserGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted.
        /// </summary>
        internal static string CarAcceptanceStatus_Accepted {
            get {
                return ResourceManager.GetString("CarAcceptanceStatus_Accepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        internal static string CarAcceptanceStatus_Pending {
            get {
                return ResourceManager.GetString("CarAcceptanceStatus_Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected.
        /// </summary>
        internal static string CarAcceptanceStatus_Rejected {
            get {
                return ResourceManager.GetString("CarAcceptanceStatus_Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acura.
        /// </summary>
        internal static string CarBrand_Acura {
            get {
                return ResourceManager.GetString("CarBrand_Acura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audi.
        /// </summary>
        internal static string CarBrand_Audi {
            get {
                return ResourceManager.GetString("CarBrand_Audi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BMW.
        /// </summary>
        internal static string CarBrand_BMW {
            get {
                return ResourceManager.GetString("CarBrand_BMW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buick.
        /// </summary>
        internal static string CarBrand_Buick {
            get {
                return ResourceManager.GetString("CarBrand_Buick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadillac.
        /// </summary>
        internal static string CarBrand_Cadillac {
            get {
                return ResourceManager.GetString("CarBrand_Cadillac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chevrolet.
        /// </summary>
        internal static string CarBrand_Chevrolet {
            get {
                return ResourceManager.GetString("CarBrand_Chevrolet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chrysler.
        /// </summary>
        internal static string CarBrand_Chrysler {
            get {
                return ResourceManager.GetString("CarBrand_Chrysler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodge.
        /// </summary>
        internal static string CarBrand_Dodge {
            get {
                return ResourceManager.GetString("CarBrand_Dodge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ford.
        /// </summary>
        internal static string CarBrand_Ford {
            get {
                return ResourceManager.GetString("CarBrand_Ford", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Honda.
        /// </summary>
        internal static string CarBrand_Honda {
            get {
                return ResourceManager.GetString("CarBrand_Honda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hyundai.
        /// </summary>
        internal static string CarBrand_Hyundai {
            get {
                return ResourceManager.GetString("CarBrand_Hyundai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jaguar.
        /// </summary>
        internal static string CarBrand_Jaguar {
            get {
                return ResourceManager.GetString("CarBrand_Jaguar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jeep.
        /// </summary>
        internal static string CarBrand_Jeep {
            get {
                return ResourceManager.GetString("CarBrand_Jeep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kia.
        /// </summary>
        internal static string CarBrand_Kia {
            get {
                return ResourceManager.GetString("CarBrand_Kia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Land Rover.
        /// </summary>
        internal static string CarBrand_LandRover {
            get {
                return ResourceManager.GetString("CarBrand_LandRover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lexus.
        /// </summary>
        internal static string CarBrand_Lexus {
            get {
                return ResourceManager.GetString("CarBrand_Lexus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mazda.
        /// </summary>
        internal static string CarBrand_Mazda {
            get {
                return ResourceManager.GetString("CarBrand_Mazda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mercedes.
        /// </summary>
        internal static string CarBrand_Mercedes {
            get {
                return ResourceManager.GetString("CarBrand_Mercedes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mitsubishi.
        /// </summary>
        internal static string CarBrand_Mitsubishi {
            get {
                return ResourceManager.GetString("CarBrand_Mitsubishi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nissan.
        /// </summary>
        internal static string CarBrand_Nissan {
            get {
                return ResourceManager.GetString("CarBrand_Nissan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string CarBrand_Other {
            get {
                return ResourceManager.GetString("CarBrand_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Porsche.
        /// </summary>
        internal static string CarBrand_Porsche {
            get {
                return ResourceManager.GetString("CarBrand_Porsche", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subaru.
        /// </summary>
        internal static string CarBrand_Subaru {
            get {
                return ResourceManager.GetString("CarBrand_Subaru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toyota.
        /// </summary>
        internal static string CarBrand_Toyota {
            get {
                return ResourceManager.GetString("CarBrand_Toyota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volkswagen.
        /// </summary>
        internal static string CarBrand_Volkswagen {
            get {
                return ResourceManager.GetString("CarBrand_Volkswagen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volvo.
        /// </summary>
        internal static string CarBrand_Volvo {
            get {
                return ResourceManager.GetString("CarBrand_Volvo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car Rental Order Not Found.
        /// </summary>
        internal static string CarRentalOrderNotFound {
            get {
                return ResourceManager.GetString("CarRentalOrderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car Rental Order Not Pending.
        /// </summary>
        internal static string CarRentalOrderNotPending {
            get {
                return ResourceManager.GetString("CarRentalOrderNotPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Not Found.
        /// </summary>
        internal static string CustomerNotFound {
            get {
                return ResourceManager.GetString("CustomerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string CustomerStatus_Active {
            get {
                return ResourceManager.GetString("CustomerStatus_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        internal static string CustomerStatus_Inactive {
            get {
                return ResourceManager.GetString("CustomerStatus_Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suspended.
        /// </summary>
        internal static string CustomerStatus_Suspended {
            get {
                return ResourceManager.GetString("CustomerStatus_Suspended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designated Places Not Found.
        /// </summary>
        internal static string DesignatedPlacesNotFound {
            get {
                return ResourceManager.GetString("DesignatedPlacesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Airport.
        /// </summary>
        internal static string Destiantion_FromAirport {
            get {
                return ResourceManager.GetString("Destiantion_FromAirport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string Destiantion_Other {
            get {
                return ResourceManager.GetString("Destiantion_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Airport.
        /// </summary>
        internal static string Destiantion_ToAirport {
            get {
                return ResourceManager.GetString("Destiantion_ToAirport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount Not Added.
        /// </summary>
        internal static string DiscountNotAdded {
            get {
                return ResourceManager.GetString("DiscountNotAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount Not Found.
        /// </summary>
        internal static string DiscountNotFound {
            get {
                return ResourceManager.GetString("DiscountNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount Not Updated.
        /// </summary>
        internal static string DiscountNotUpdated {
            get {
                return ResourceManager.GetString("DiscountNotUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount Not Valid.
        /// </summary>
        internal static string DiscountNotValid {
            get {
                return ResourceManager.GetString("DiscountNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car Rental Service.
        /// </summary>
        internal static string DiscountServices_CarRentalService {
            get {
                return ResourceManager.GetString("DiscountServices_CarRentalService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal Ride Service.
        /// </summary>
        internal static string DiscountServices_NormalRideService {
            get {
                return ResourceManager.GetString("DiscountServices_NormalRideService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIP Ride Service.
        /// </summary>
        internal static string DiscountServices_VipRideService {
            get {
                return ResourceManager.GetString("DiscountServices_VipRideService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver Not Allowed.
        /// </summary>
        internal static string DriverNotAllowed {
            get {
                return ResourceManager.GetString("DriverNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver Not Found.
        /// </summary>
        internal static string DriverNotFound {
            get {
                return ResourceManager.GetString("DriverNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        internal static string DriverStatus_Available {
            get {
                return ResourceManager.GetString("DriverStatus_Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline.
        /// </summary>
        internal static string DriverStatus_Offline {
            get {
                return ResourceManager.GetString("DriverStatus_Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Ride.
        /// </summary>
        internal static string DriverStatus_OnRide {
            get {
                return ResourceManager.GetString("DriverStatus_OnRide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suspended.
        /// </summary>
        internal static string DriverStatus_Suspended {
            get {
                return ResourceManager.GetString("DriverStatus_Suspended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed To Create Car Rental Order.
        /// </summary>
        internal static string FailedToCreateCarRentalOrder {
            get {
                return ResourceManager.GetString("FailedToCreateCarRentalOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed To Create Designated Places.
        /// </summary>
        internal static string FailedToCreateDesignatedPlaces {
            get {
                return ResourceManager.GetString("FailedToCreateDesignatedPlaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed To Create Notification Template.
        /// </summary>
        internal static string FailedToCreateNotificationTemplate {
            get {
                return ResourceManager.GetString("FailedToCreateNotificationTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed To Create Rent Car.
        /// </summary>
        internal static string FailedToCreateRentCar {
            get {
                return ResourceManager.GetString("FailedToCreateRentCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed To Create Ride.
        /// </summary>
        internal static string FailedToCreateRide {
            get {
                return ResourceManager.GetString("FailedToCreateRide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed To Create Ride Billing.
        /// </summary>
        internal static string FailedToCreateRideBilling {
            get {
                return ResourceManager.GetString("FailedToCreateRideBilling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed To Create Support Ticket.
        /// </summary>
        internal static string FailedToCreateSupportTicket {
            get {
                return ResourceManager.GetString("FailedToCreateSupportTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed To Create User Notification.
        /// </summary>
        internal static string FailedToCreateUserNotification {
            get {
                return ResourceManager.GetString("FailedToCreateUserNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed To Create Vehicle.
        /// </summary>
        internal static string FailedToCreateVehicle {
            get {
                return ResourceManager.GetString("FailedToCreateVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create warehouse.
        /// </summary>
        internal static string FailedToCreateWarehouse {
            get {
                return ResourceManager.GetString("FailedToCreateWarehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed To Delete Ride Billing.
        /// </summary>
        internal static string FailedToDeleteRideBilling {
            get {
                return ResourceManager.GetString("FailedToDeleteRideBilling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed To Delete Support Ticket.
        /// </summary>
        internal static string FailedToDeleteSupportTicket {
            get {
                return ResourceManager.GetString("FailedToDeleteSupportTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed To Get Ride Billing.
        /// </summary>
        internal static string FailedToGetRideBilling {
            get {
                return ResourceManager.GetString("FailedToGetRideBilling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed To Update Car Rental Order.
        /// </summary>
        internal static string FailedToUpdateCarRentalOrder {
            get {
                return ResourceManager.GetString("FailedToUpdateCarRentalOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed To Update Designated Places.
        /// </summary>
        internal static string FailedToUpdateDesignatedPlaces {
            get {
                return ResourceManager.GetString("FailedToUpdateDesignatedPlaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed To Update Rent Car.
        /// </summary>
        internal static string FailedToUpdateRentCar {
            get {
                return ResourceManager.GetString("FailedToUpdateRentCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed To Update Ride.
        /// </summary>
        internal static string FailedToUpdateRide {
            get {
                return ResourceManager.GetString("FailedToUpdateRide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed To Update Support Ticket.
        /// </summary>
        internal static string FailedToUpdateSupportTicket {
            get {
                return ResourceManager.GetString("FailedToUpdateSupportTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed To Update User Groups.
        /// </summary>
        internal static string FailedToUpdateUserGroups {
            get {
                return ResourceManager.GetString("FailedToUpdateUserGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed To Update Vehicle.
        /// </summary>
        internal static string FailedToUpdateVehicle {
            get {
                return ResourceManager.GetString("FailedToUpdateVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update warehouse.
        /// </summary>
        internal static string FailedToUpdateWarehouse {
            get {
                return ResourceManager.GetString("FailedToUpdateWarehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favourite Place Not Added.
        /// </summary>
        internal static string FavouritePlaceNotAdded {
            get {
                return ResourceManager.GetString("FavouritePlaceNotAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favourite Place Not Found.
        /// </summary>
        internal static string FavouritePlaceNotFound {
            get {
                return ResourceManager.GetString("FavouritePlaceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favourite Place Not Updated.
        /// </summary>
        internal static string FavouritePlaceNotUpdated {
            get {
                return ResourceManager.GetString("FavouritePlaceNotUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Password or Phone Number.
        /// </summary>
        internal static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Ride Status.
        /// </summary>
        internal static string InvalidRideStatus {
            get {
                return ResourceManager.GetString("InvalidRideStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anbar.
        /// </summary>
        internal static string IraqGovernorates_Anbar {
            get {
                return ResourceManager.GetString("IraqGovernorates_Anbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Babil.
        /// </summary>
        internal static string IraqGovernorates_Babil {
            get {
                return ResourceManager.GetString("IraqGovernorates_Babil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baghdad.
        /// </summary>
        internal static string IraqGovernorates_Baghdad {
            get {
                return ResourceManager.GetString("IraqGovernorates_Baghdad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basra.
        /// </summary>
        internal static string IraqGovernorates_Basra {
            get {
                return ResourceManager.GetString("IraqGovernorates_Basra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dhi Qar.
        /// </summary>
        internal static string IraqGovernorates_DhiQar {
            get {
                return ResourceManager.GetString("IraqGovernorates_DhiQar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diyala.
        /// </summary>
        internal static string IraqGovernorates_Diyala {
            get {
                return ResourceManager.GetString("IraqGovernorates_Diyala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dohuk.
        /// </summary>
        internal static string IraqGovernorates_Dohuk {
            get {
                return ResourceManager.GetString("IraqGovernorates_Dohuk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erbil.
        /// </summary>
        internal static string IraqGovernorates_Erbil {
            get {
                return ResourceManager.GetString("IraqGovernorates_Erbil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Karbala.
        /// </summary>
        internal static string IraqGovernorates_Karbala {
            get {
                return ResourceManager.GetString("IraqGovernorates_Karbala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kirkuk.
        /// </summary>
        internal static string IraqGovernorates_Kirkuk {
            get {
                return ResourceManager.GetString("IraqGovernorates_Kirkuk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maysan.
        /// </summary>
        internal static string IraqGovernorates_Maysan {
            get {
                return ResourceManager.GetString("IraqGovernorates_Maysan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muthanna.
        /// </summary>
        internal static string IraqGovernorates_Muthanna {
            get {
                return ResourceManager.GetString("IraqGovernorates_Muthanna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Najaf.
        /// </summary>
        internal static string IraqGovernorates_Najaf {
            get {
                return ResourceManager.GetString("IraqGovernorates_Najaf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qadisiyyah.
        /// </summary>
        internal static string IraqGovernorates_Qadisiyyah {
            get {
                return ResourceManager.GetString("IraqGovernorates_Qadisiyyah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salah Al-Din.
        /// </summary>
        internal static string IraqGovernorates_SalahAlDin {
            get {
                return ResourceManager.GetString("IraqGovernorates_SalahAlDin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sulaymaniyah.
        /// </summary>
        internal static string IraqGovernorates_Sulaymaniyah {
            get {
                return ResourceManager.GetString("IraqGovernorates_Sulaymaniyah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wasit.
        /// </summary>
        internal static string IraqGovernorates_Wasit {
            get {
                return ResourceManager.GetString("IraqGovernorates_Wasit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduled.
        /// </summary>
        internal static string NotificationStatus_Scheduled {
            get {
                return ResourceManager.GetString("NotificationStatus_Scheduled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent.
        /// </summary>
        internal static string NotificationStatus_Sent {
            get {
                return ResourceManager.GetString("NotificationStatus_Sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Template Not Found.
        /// </summary>
        internal static string NotificationTemplateNotFound {
            get {
                return ResourceManager.GetString("NotificationTemplateNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount.
        /// </summary>
        internal static string NotificationType_Discount {
            get {
                return ResourceManager.GetString("NotificationType_Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string NotificationType_Error {
            get {
                return ResourceManager.GetString("NotificationType_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string NotificationType_Info {
            get {
                return ResourceManager.GetString("NotificationType_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string NotificationType_Other {
            get {
                return ResourceManager.GetString("NotificationType_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promotion.
        /// </summary>
        internal static string NotificationType_Promotion {
            get {
                return ResourceManager.GetString("NotificationType_Promotion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Update.
        /// </summary>
        internal static string NotificationType_SystemUpdate {
            get {
                return ResourceManager.GetString("NotificationType_SystemUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string NotificationType_Warning {
            get {
                return ResourceManager.GetString("NotificationType_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Reset Successfully.
        /// </summary>
        internal static string PasswordResetSuccessfully {
            get {
                return ResourceManager.GetString("PasswordResetSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid.
        /// </summary>
        internal static string PaymentStatus_Paid {
            get {
                return ResourceManager.GetString("PaymentStatus_Paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpaid.
        /// </summary>
        internal static string PaymentStatus_UnPaid {
            get {
                return ResourceManager.GetString("PaymentStatus_UnPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chosen Location.
        /// </summary>
        internal static string PickUpType_ChosenLocation {
            get {
                return ResourceManager.GetString("PickUpType_ChosenLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From warehouse.
        /// </summary>
        internal static string PickUpType_FromWareHouse {
            get {
                return ResourceManager.GetString("PickUpType_FromWareHouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apartment.
        /// </summary>
        internal static string PlaceType_Apartment {
            get {
                return ResourceManager.GetString("PlaceType_Apartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string PlaceType_Home {
            get {
                return ResourceManager.GetString("PlaceType_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string PlaceType_Other {
            get {
                return ResourceManager.GetString("PlaceType_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work.
        /// </summary>
        internal static string PlaceType_Work {
            get {
                return ResourceManager.GetString("PlaceType_Work", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled.
        /// </summary>
        internal static string RentalOrderStatus_Canceled {
            get {
                return ResourceManager.GetString("RentalOrderStatus_Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car is back.
        /// </summary>
        internal static string RentalOrderStatus_CarBack {
            get {
                return ResourceManager.GetString("RentalOrderStatus_CarBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car Not Back.
        /// </summary>
        internal static string RentalOrderStatus_CarNotBack {
            get {
                return ResourceManager.GetString("RentalOrderStatus_CarNotBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        internal static string RentalOrderStatus_Completed {
            get {
                return ResourceManager.GetString("RentalOrderStatus_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmed.
        /// </summary>
        internal static string RentalOrderStatus_Confirmed {
            get {
                return ResourceManager.GetString("RentalOrderStatus_Confirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dropped Off.
        /// </summary>
        internal static string RentalOrderStatus_DroppedOff {
            get {
                return ResourceManager.GetString("RentalOrderStatus_DroppedOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        internal static string RentalOrderStatus_Pending {
            get {
                return ResourceManager.GetString("RentalOrderStatus_Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picked Up.
        /// </summary>
        internal static string RentalOrderStatus_PickedUp {
            get {
                return ResourceManager.GetString("RentalOrderStatus_PickedUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected.
        /// </summary>
        internal static string RentalOrderStatus_Rejected {
            get {
                return ResourceManager.GetString("RentalOrderStatus_Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rent Car Not Found.
        /// </summary>
        internal static string RentCarNotFound {
            get {
                return ResourceManager.GetString("RentCarNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Not Found.
        /// </summary>
        internal static string ReviewNotFound {
            get {
                return ResourceManager.GetString("ReviewNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RideBilling Type Already Exist.
        /// </summary>
        internal static string RideBillingTypeAlreadyExist {
            get {
                return ResourceManager.GetString("RideBillingTypeAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ride Not Arrived At Pickup.
        /// </summary>
        internal static string RideNotArrivedAtPickup {
            get {
                return ResourceManager.GetString("RideNotArrivedAtPickup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ride Not Found.
        /// </summary>
        internal static string RideNotFound {
            get {
                return ResourceManager.GetString("RideNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card.
        /// </summary>
        internal static string RidePaymentType_Card {
            get {
                return ResourceManager.GetString("RidePaymentType_Card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash.
        /// </summary>
        internal static string RidePaymentType_Cash {
            get {
                return ResourceManager.GetString("RidePaymentType_Cash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallet.
        /// </summary>
        internal static string RidePaymentType_Wallet {
            get {
                return ResourceManager.GetString("RidePaymentType_Wallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrived At Detour.
        /// </summary>
        internal static string RideStatus_ArrivedAtDetour {
            get {
                return ResourceManager.GetString("RideStatus_ArrivedAtDetour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrived At Pickup.
        /// </summary>
        internal static string RideStatus_ArrivedAtPickup {
            get {
                return ResourceManager.GetString("RideStatus_ArrivedAtPickup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled.
        /// </summary>
        internal static string RideStatus_Canceled {
            get {
                return ResourceManager.GetString("RideStatus_Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        internal static string RideStatus_Completed {
            get {
                return ResourceManager.GetString("RideStatus_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmed.
        /// </summary>
        internal static string RideStatus_Confirmed {
            get {
                return ResourceManager.GetString("RideStatus_Confirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        internal static string RideStatus_Pending {
            get {
                return ResourceManager.GetString("RideStatus_Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected.
        /// </summary>
        internal static string RideStatus_Rejected {
            get {
                return ResourceManager.GetString("RideStatus_Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started.
        /// </summary>
        internal static string RideStatus_Started {
            get {
                return ResourceManager.GetString("RideStatus_Started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string RideType_Normal {
            get {
                return ResourceManager.GetString("RideType_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal From Airport.
        /// </summary>
        internal static string RideType_Normal_From_Airport {
            get {
                return ResourceManager.GetString("RideType_Normal_From_Airport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal Outside City.
        /// </summary>
        internal static string RideType_Normal_OutSide_City {
            get {
                return ResourceManager.GetString("RideType_Normal_OutSide_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal To Airport.
        /// </summary>
        internal static string RideType_Normal_To_Airport {
            get {
                return ResourceManager.GetString("RideType_Normal_To_Airport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal To Al Muthana.
        /// </summary>
        internal static string RideType_Normal_To_AlMuthana {
            get {
                return ResourceManager.GetString("RideType_Normal_To_AlMuthana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal To Babil.
        /// </summary>
        internal static string RideType_Normal_To_Babil {
            get {
                return ResourceManager.GetString("RideType_Normal_To_Babil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal To Dhi Qar.
        /// </summary>
        internal static string RideType_Normal_To_DhiQar {
            get {
                return ResourceManager.GetString("RideType_Normal_To_DhiQar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal To Karbala.
        /// </summary>
        internal static string RideType_Normal_To_Karbala {
            get {
                return ResourceManager.GetString("RideType_Normal_To_Karbala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal To Maysan.
        /// </summary>
        internal static string RideType_Normal_To_Maysan {
            get {
                return ResourceManager.GetString("RideType_Normal_To_Maysan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal To Najaf.
        /// </summary>
        internal static string RideType_Normal_To_Najaf {
            get {
                return ResourceManager.GetString("RideType_Normal_To_Najaf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal To Qadisiyah.
        /// </summary>
        internal static string RideType_Normal_To_Qadisiyah {
            get {
                return ResourceManager.GetString("RideType_Normal_To_Qadisiyah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal To Samawa.
        /// </summary>
        internal static string RideType_Normal_To_Samawa {
            get {
                return ResourceManager.GetString("RideType_Normal_To_Samawa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal To Wasit.
        /// </summary>
        internal static string RideType_Normal_To_Wasit {
            get {
                return ResourceManager.GetString("RideType_Normal_To_Wasit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vip.
        /// </summary>
        internal static string RideType_Vip {
            get {
                return ResourceManager.GetString("RideType_Vip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIP From Airport.
        /// </summary>
        internal static string RideType_Vip_From_Airport {
            get {
                return ResourceManager.GetString("RideType_Vip_From_Airport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIP Outside City.
        /// </summary>
        internal static string RideType_Vip_OutSide_City {
            get {
                return ResourceManager.GetString("RideType_Vip_OutSide_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIP To Airport.
        /// </summary>
        internal static string RideType_Vip_To_Airport {
            get {
                return ResourceManager.GetString("RideType_Vip_To_Airport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIP To Al Muthana.
        /// </summary>
        internal static string RideType_Vip_To_AlMuthana {
            get {
                return ResourceManager.GetString("RideType_Vip_To_AlMuthana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIP To Babil.
        /// </summary>
        internal static string RideType_Vip_To_Babil {
            get {
                return ResourceManager.GetString("RideType_Vip_To_Babil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIP To Dhi Qar.
        /// </summary>
        internal static string RideType_Vip_To_DhiQar {
            get {
                return ResourceManager.GetString("RideType_Vip_To_DhiQar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIP To Karbala.
        /// </summary>
        internal static string RideType_Vip_To_Karbala {
            get {
                return ResourceManager.GetString("RideType_Vip_To_Karbala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIP To Maysan.
        /// </summary>
        internal static string RideType_Vip_To_Maysan {
            get {
                return ResourceManager.GetString("RideType_Vip_To_Maysan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIP To Najaf.
        /// </summary>
        internal static string RideType_Vip_To_Najaf {
            get {
                return ResourceManager.GetString("RideType_Vip_To_Najaf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIP To Qadisiyah.
        /// </summary>
        internal static string RideType_Vip_To_Qadisiyah {
            get {
                return ResourceManager.GetString("RideType_Vip_To_Qadisiyah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIP To Samawa.
        /// </summary>
        internal static string RideType_Vip_To_Samawa {
            get {
                return ResourceManager.GetString("RideType_Vip_To_Samawa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIP To Wasit.
        /// </summary>
        internal static string RideType_Vip_To_Wasit {
            get {
                return ResourceManager.GetString("RideType_Vip_To_Wasit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to admin.
        /// </summary>
        internal static string Roles_Admin {
            get {
                return ResourceManager.GetString("Roles_Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch Manager.
        /// </summary>
        internal static string Roles_BranchManager {
            get {
                return ResourceManager.GetString("Roles_BranchManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to customer.
        /// </summary>
        internal static string Roles_Customer {
            get {
                return ResourceManager.GetString("Roles_Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to driver.
        /// </summary>
        internal static string Roles_Driver {
            get {
                return ResourceManager.GetString("Roles_Driver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings Not Found.
        /// </summary>
        internal static string SettingsNotFound {
            get {
                return ResourceManager.GetString("SettingsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic.
        /// </summary>
        internal static string ShifterType_Automatic {
            get {
                return ResourceManager.GetString("ShifterType_Automatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual.
        /// </summary>
        internal static string ShifterType_Manual {
            get {
                return ResourceManager.GetString("ShifterType_Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support Ticket Not Found.
        /// </summary>
        internal static string SupportTicketNotFound {
            get {
                return ResourceManager.GetString("SupportTicketNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        internal static string TicketStatus_Closed {
            get {
                return ResourceManager.GetString("TicketStatus_Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Progress.
        /// </summary>
        internal static string TicketStatus_InProgress {
            get {
                return ResourceManager.GetString("TicketStatus_InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string TicketStatus_Open {
            get {
                return ResourceManager.GetString("TicketStatus_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complaint.
        /// </summary>
        internal static string TicketType_Complaint {
            get {
                return ResourceManager.GetString("TicketType_Complaint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string TicketType_General {
            get {
                return ResourceManager.GetString("TicketType_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inquiry.
        /// </summary>
        internal static string TicketType_Inquiry {
            get {
                return ResourceManager.GetString("TicketType_Inquiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string TicketType_Other {
            get {
                return ResourceManager.GetString("TicketType_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment.
        /// </summary>
        internal static string TicketType_Payment {
            get {
                return ResourceManager.GetString("TicketType_Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refund.
        /// </summary>
        internal static string TicketType_Refund {
            get {
                return ResourceManager.GetString("TicketType_Refund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggestion.
        /// </summary>
        internal static string TicketType_Suggestion {
            get {
                return ResourceManager.GetString("TicketType_Suggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical.
        /// </summary>
        internal static string TicketType_Technical {
            get {
                return ResourceManager.GetString("TicketType_Technical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Already Exists..
        /// </summary>
        internal static string UserAlreadyExists {
            get {
                return ResourceManager.GetString("UserAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Groups Not Found.
        /// </summary>
        internal static string UserGroupsNotFound {
            get {
                return ResourceManager.GetString("UserGroupsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Is Not A Customer.
        /// </summary>
        internal static string UserIsNotACustomer {
            get {
                return ResourceManager.GetString("UserIsNotACustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Is Not A Driver.
        /// </summary>
        internal static string UserIsNotADriver {
            get {
                return ResourceManager.GetString("UserIsNotADriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Is Not An Admin.
        /// </summary>
        internal static string UserIsNotAnAdmin {
            get {
                return ResourceManager.GetString("UserIsNotAnAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Not Allowed.
        /// </summary>
        internal static string UserNotAllowed {
            get {
                return ResourceManager.GetString("UserNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Not Authenticated.
        /// </summary>
        internal static string UserNotAuthenticated {
            get {
                return ResourceManager.GetString("UserNotAuthenticated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Not Found.
        /// </summary>
        internal static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Notification Not Found.
        /// </summary>
        internal static string UserNotificationNotFound {
            get {
                return ResourceManager.GetString("UserNotificationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Not Available.
        /// </summary>
        internal static string VehicleNotAvailable {
            get {
                return ResourceManager.GetString("VehicleNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Not For Rent.
        /// </summary>
        internal static string VehicleNotForRent {
            get {
                return ResourceManager.GetString("VehicleNotForRent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Not Found.
        /// </summary>
        internal static string VehicleNotFound {
            get {
                return ResourceManager.GetString("VehicleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        internal static string VehicleStatus_Available {
            get {
                return ResourceManager.GetString("VehicleStatus_Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Maintenance.
        /// </summary>
        internal static string VehicleStatus_InMaintenance {
            get {
                return ResourceManager.GetString("VehicleStatus_InMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Available.
        /// </summary>
        internal static string VehicleStatus_NotAvailable {
            get {
                return ResourceManager.GetString("VehicleStatus_NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Trip.
        /// </summary>
        internal static string VehicleStatus_OnTrip {
            get {
                return ResourceManager.GetString("VehicleStatus_OnTrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out of Service.
        /// </summary>
        internal static string VehicleStatus_OutOfService {
            get {
                return ResourceManager.GetString("VehicleStatus_OutOfService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string VehicleType_Normal {
            get {
                return ResourceManager.GetString("VehicleType_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rental.
        /// </summary>
        internal static string VehicleType_Rental {
            get {
                return ResourceManager.GetString("VehicleType_Rental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIP.
        /// </summary>
        internal static string VehicleType_Vip {
            get {
                return ResourceManager.GetString("VehicleType_Vip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warehouse Not Found.
        /// </summary>
        internal static string WarehouseNotFound {
            get {
                return ResourceManager.GetString("WarehouseNotFound", resourceCulture);
            }
        }
    }
}
